name: Build Docker Image

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn

    - name: Run tests
      run: yarn jest

    - name: Build Docker image
      run: |
        docker build -t memoriesofthenile .


